import {
  MessageSquare, Brain, Wrench, Globe, GitBranch, Repeat,
  Database, Send, Code, Wifi, Route, Shuffle, Bot,
  Mail, FileText, FileType, Globe2, Video,
  // v0.4.2 icons
  ArrowLeftRight, Filter, Split, Merge, Clock,
  Tags, Smile, FileSearch, AlignLeft, MessageCircleQuestion,
  Timer, Webhook, MessageSquarePlus,
  ArrowUpDown, Sigma, ListFilter, Calculator, Search, BookOpen,
} from 'lucide-react';

export const NODE_CATEGORIES = {
  'Input/Output': {
    color: 'var(--node-io)',
    colorClass: 'node-io',
    nodes: ['InputNode', 'OutputNode'],
  },
  'AI / LLM': {
    color: 'var(--node-ai)',
    colorClass: 'node-ai',
    nodes: ['LLMNode', 'MemoryNode'],
  },
  'AI Processing': {
    color: 'var(--node-aiproc)',
    colorClass: 'node-aiproc',
    nodes: ['TextClassifierNode', 'SentimentNode', 'InfoExtractorNode', 'SummarizerNode', 'QAChainNode'],
  },
  'Triggers': {
    color: 'var(--node-trigger)',
    colorClass: 'node-trigger',
    nodes: ['ScheduleTriggerNode', 'WebhookTriggerNode', 'ChatTriggerNode'],
  },
  'Tools': {
    color: 'var(--node-tool)',
    colorClass: 'node-tool',
    nodes: ['ToolNode', 'ScraperNode', 'HTTPNode', 'CodeNode', 'CalculatorNode', 'SearchNode', 'WikipediaNode'],
  },
  'Control Flow': {
    color: 'var(--node-flow)',
    colorClass: 'node-flow',
    nodes: ['ConditionNode', 'LoopNode', 'RouterNode', 'SwitchNode', 'FilterNode', 'SplitNode', 'MergeNode', 'WaitNode'],
  },
  'Data': {
    color: 'var(--node-data)',
    colorClass: 'node-data',
    nodes: ['TransformNode', 'SubAgentNode', 'SortNode', 'AggregateNode', 'DeduplicateNode'],
  },
  'Actions': {
    color: 'var(--node-action)',
    colorClass: 'node-action',
    nodes: ['EmailNode', 'PDFNode', 'DocxNode', 'BlogNode', 'VideoNode'],
  },
};

export const NODE_DEFINITIONS = {
  InputNode: {
    label: 'Input',
    icon: MessageSquare,
    category: 'Input/Output',
    color: 'var(--node-io)',
    description: 'User input or trigger',
    defaultData: {
      label: 'User Input',
      inputType: 'text',
      schema: null,
      description: '',
    },
  },
  OutputNode: {
    label: 'Output',
    icon: Send,
    category: 'Input/Output',
    color: 'var(--node-io)',
    description: 'Final response or result',
    defaultData: {
      label: 'Output',
      outputFormat: 'text',
      schema: null,
    },
  },
  LLMNode: {
    label: 'LLM',
    icon: Brain,
    category: 'AI / LLM',
    color: 'var(--node-ai)',
    description: 'AI model call (Claude, GPT, MiniMax, Kimi, etc.)',
    defaultData: {
      label: 'LLM Call',
      provider: 'claude',
      model: 'claude-sonnet-4-6',
      systemPrompt: '',
      temperature: 0.7,
      maxTokens: 4096,
    },
  },
  MemoryNode: {
    label: 'Memory',
    icon: Database,
    category: 'AI / LLM',
    color: 'var(--node-ai)',
    description: 'Conversation or vector memory',
    defaultData: {
      label: 'Memory',
      memoryType: 'buffer',
      maxMessages: 20,
    },
  },
  ToolNode: {
    label: 'Tool',
    icon: Wrench,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Execute a tool or function',
    defaultData: {
      label: 'Tool',
      toolType: 'api',
      config: {},
    },
  },
  ScraperNode: {
    label: 'Scraper',
    icon: Globe,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Scrape web content',
    defaultData: {
      label: 'Web Scraper',
      url: '',
      selector: '',
      format: 'markdown',
    },
  },
  HTTPNode: {
    label: 'HTTP',
    icon: Wifi,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Make HTTP API calls',
    defaultData: {
      label: 'HTTP Request',
      method: 'GET',
      url: '',
      headers: {},
      body: null,
    },
  },
  CodeNode: {
    label: 'Code',
    icon: Code,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Run JavaScript or Python code',
    defaultData: {
      label: 'Code',
      language: 'javascript',
      code: '// Transform data here\nreturn input;',
    },
  },
  ConditionNode: {
    label: 'Condition',
    icon: GitBranch,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'If/else branching logic',
    defaultData: {
      label: 'Condition',
      conditions: [],
      trueLabel: 'Yes',
      falseLabel: 'No',
    },
  },
  LoopNode: {
    label: 'Loop',
    icon: Repeat,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Iterate or retry',
    defaultData: {
      label: 'Loop',
      maxIterations: 10,
      stopCondition: '',
    },
  },
  RouterNode: {
    label: 'Router',
    icon: Route,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Route to different paths',
    defaultData: {
      label: 'Router',
      routes: [{ label: 'Route A', condition: '' }],
    },
  },
  TransformNode: {
    label: 'Transform',
    icon: Shuffle,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Transform or map data',
    defaultData: {
      label: 'Transform',
      transformType: 'template',
      expression: '',
    },
  },
  SubAgentNode: {
    label: 'Sub-Agent',
    icon: Bot,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Call another agent',
    defaultData: {
      label: 'Sub-Agent',
      agentId: '',
      inputMapping: {},
    },
  },
  EmailNode: {
    label: 'Email',
    icon: Mail,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Send email via SMTP',
    defaultData: {
      label: 'Send Email',
      to: '',
      cc: '',
      bcc: '',
      subject: '',
      bodyTemplate: '{{input}}',
      attachFromUpstream: false,
    },
  },
  PDFNode: {
    label: 'PDF',
    icon: FileText,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Generate PDF document',
    defaultData: {
      label: 'Generate PDF',
      filenameTemplate: 'output-{{date}}',
      pageSize: 'A4',
      margins: { top: 40, bottom: 40, left: 40, right: 40 },
      includeHeader: false,
      headerText: '',
      includeFooter: false,
      footerText: '',
    },
  },
  DocxNode: {
    label: 'DOCX',
    icon: FileType,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Generate Word document',
    defaultData: {
      label: 'Generate DOCX',
      filenameTemplate: 'document-{{date}}',
      documentTitle: '',
      fontSize: 12,
      fontFamily: 'Arial',
    },
  },
  BlogNode: {
    label: 'Blog',
    icon: Globe2,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Render markdown to styled HTML',
    defaultData: {
      label: 'Generate Blog',
      filenameTemplate: 'blog-{{date}}',
      cssTheme: 'modern',
      pageTitle: '',
      metaDescription: '',
      includeTableOfContents: false,
    },
  },
  VideoNode: {
    label: 'Video',
    icon: Video,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Compose video from media',
    defaultData: {
      label: 'Create Video',
      filenameTemplate: 'video-{{date}}',
      inputType: 'single_image_with_audio',
      audioSource: '',
      fps: 30,
      resolution: '1920x1080',
      codec: 'libx264',
    },
  },

  /* ─── v0.4.2 — Flow Control ─── */
  SwitchNode: {
    label: 'Switch',
    icon: ArrowLeftRight,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Multi-way branching by value',
    defaultData: {
      label: 'Switch',
      switchField: 'value',
      cases: [
        { label: 'Case 1', value: '' },
        { label: 'Default', value: '*' },
      ],
    },
  },
  FilterNode: {
    label: 'Filter',
    icon: Filter,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Filter arrays/objects by condition',
    defaultData: {
      label: 'Filter',
      filterExpression: '',
      filterMode: 'include',
    },
  },
  SplitNode: {
    label: 'Split',
    icon: Split,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Split input into parallel streams',
    defaultData: {
      label: 'Split',
      splitCount: 2,
      splitBy: 'items',
    },
  },
  MergeNode: {
    label: 'Merge',
    icon: Merge,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Combine multiple inputs into one',
    defaultData: {
      label: 'Merge',
      mergeMode: 'append',
    },
  },
  WaitNode: {
    label: 'Wait',
    icon: Clock,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Pause execution for a duration',
    defaultData: {
      label: 'Wait',
      waitDuration: 1,
      waitUnit: 'seconds',
    },
  },

  /* ─── v0.4.2 — AI Processing ─── */
  TextClassifierNode: {
    label: 'Text Classifier',
    icon: Tags,
    category: 'AI Processing',
    color: 'var(--node-aiproc)',
    description: 'Classify text into categories via LLM',
    defaultData: {
      label: 'Text Classifier',
      categories: ['positive', 'negative', 'neutral'],
      multiLabel: false,
    },
  },
  SentimentNode: {
    label: 'Sentiment',
    icon: Smile,
    category: 'AI Processing',
    color: 'var(--node-aiproc)',
    description: 'Analyze sentiment of text via LLM',
    defaultData: {
      label: 'Sentiment Analysis',
      outputFormat: 'json',
      granularity: 'document',
    },
  },
  InfoExtractorNode: {
    label: 'Info Extractor',
    icon: FileSearch,
    category: 'AI Processing',
    color: 'var(--node-aiproc)',
    description: 'Extract structured data from text via LLM',
    defaultData: {
      label: 'Info Extractor',
      extractionFields: ['name', 'email', 'phone'],
    },
  },
  SummarizerNode: {
    label: 'Summarizer',
    icon: AlignLeft,
    category: 'AI Processing',
    color: 'var(--node-aiproc)',
    description: 'Summarize long content via LLM',
    defaultData: {
      label: 'Summarizer',
      maxLength: 200,
      summaryStyle: 'concise',
    },
  },
  QAChainNode: {
    label: 'Q&A Chain',
    icon: MessageCircleQuestion,
    category: 'AI Processing',
    color: 'var(--node-aiproc)',
    description: 'Answer questions over provided context',
    defaultData: {
      label: 'Q&A Chain',
      contextSource: 'upstream',
      responseStyle: 'detailed',
    },
  },

  /* ─── v0.4.2 — Triggers ─── */
  ScheduleTriggerNode: {
    label: 'Schedule',
    icon: Timer,
    category: 'Triggers',
    color: 'var(--node-trigger)',
    description: 'Trigger on a cron schedule',
    defaultData: {
      label: 'Schedule Trigger',
      cronExpression: '0 * * * *',
      timezone: 'UTC',
    },
  },
  WebhookTriggerNode: {
    label: 'Webhook',
    icon: Webhook,
    category: 'Triggers',
    color: 'var(--node-trigger)',
    description: 'Trigger via HTTP webhook',
    defaultData: {
      label: 'Webhook Trigger',
      webhookMethod: 'POST',
      webhookPath: 'webhook',
    },
  },
  ChatTriggerNode: {
    label: 'Chat',
    icon: MessageSquarePlus,
    category: 'Triggers',
    color: 'var(--node-trigger)',
    description: 'Trigger from a chat message',
    defaultData: {
      label: 'Chat Trigger',
    },
  },

  /* ─── v0.4.2 — Data (Sort, Aggregate, Deduplicate) ─── */
  SortNode: {
    label: 'Sort',
    icon: ArrowUpDown,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Sort arrays by field',
    defaultData: {
      label: 'Sort',
      sortField: 'value',
      sortOrder: 'asc',
    },
  },
  AggregateNode: {
    label: 'Aggregate',
    icon: Sigma,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Aggregate/reduce data',
    defaultData: {
      label: 'Aggregate',
      aggregateOp: 'concatenate',
      aggregateField: '',
    },
  },
  DeduplicateNode: {
    label: 'Deduplicate',
    icon: ListFilter,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Remove duplicate items',
    defaultData: {
      label: 'Deduplicate',
      deduplicateField: 'auto',
    },
  },

  /* ─── v0.4.2 — Tools (Calculator, Search, Wikipedia) ─── */
  CalculatorNode: {
    label: 'Calculator',
    icon: Calculator,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Evaluate math expressions',
    defaultData: {
      label: 'Calculator',
      expression: '',
    },
  },
  SearchNode: {
    label: 'Search',
    icon: Search,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Web search via SerpApi',
    defaultData: {
      label: 'Web Search',
      searchEngine: 'SerpApi',
      maxResults: 5,
    },
  },
  WikipediaNode: {
    label: 'Wikipedia',
    icon: BookOpen,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Look up Wikipedia articles',
    defaultData: {
      label: 'Wikipedia',
      language: 'en',
      sections: 'summary',
    },
  },
};
