import {
  MessageSquare, Brain, Wrench, Globe, GitBranch, Repeat,
  Database, Send, Code, Wifi, Route, Shuffle, Bot,
  Mail, FileText, FileType, Globe2, Video
} from 'lucide-react';

export const NODE_CATEGORIES = {
  'Input/Output': {
    color: 'var(--node-io)',
    colorClass: 'node-io',
    nodes: ['InputNode', 'OutputNode'],
  },
  'AI / LLM': {
    color: 'var(--node-ai)',
    colorClass: 'node-ai',
    nodes: ['LLMNode', 'MemoryNode'],
  },
  'Tools': {
    color: 'var(--node-tool)',
    colorClass: 'node-tool',
    nodes: ['ToolNode', 'ScraperNode', 'HTTPNode', 'CodeNode'],
  },
  'Control Flow': {
    color: 'var(--node-flow)',
    colorClass: 'node-flow',
    nodes: ['ConditionNode', 'LoopNode', 'RouterNode'],
  },
  'Data': {
    color: 'var(--node-data)',
    colorClass: 'node-data',
    nodes: ['TransformNode', 'SubAgentNode'],
  },
  'Actions': {
    color: 'var(--node-action)',
    colorClass: 'node-action',
    nodes: ['EmailNode', 'PDFNode', 'DocxNode', 'BlogNode', 'VideoNode'],
  },
};

export const NODE_DEFINITIONS = {
  InputNode: {
    label: 'Input',
    icon: MessageSquare,
    category: 'Input/Output',
    color: 'var(--node-io)',
    description: 'User input or trigger',
    defaultData: {
      label: 'User Input',
      inputType: 'text',
      schema: null,
      description: '',
    },
  },
  OutputNode: {
    label: 'Output',
    icon: Send,
    category: 'Input/Output',
    color: 'var(--node-io)',
    description: 'Final response or result',
    defaultData: {
      label: 'Output',
      outputFormat: 'text',
      schema: null,
    },
  },
  LLMNode: {
    label: 'LLM',
    icon: Brain,
    category: 'AI / LLM',
    color: 'var(--node-ai)',
    description: 'AI model call (Claude, GPT, MiniMax, Kimi, etc.)',
    defaultData: {
      label: 'LLM Call',
      provider: 'claude',
      model: 'claude-sonnet-4-6',
      systemPrompt: '',
      temperature: 0.7,
      maxTokens: 4096,
    },
  },
  MemoryNode: {
    label: 'Memory',
    icon: Database,
    category: 'AI / LLM',
    color: 'var(--node-ai)',
    description: 'Conversation or vector memory',
    defaultData: {
      label: 'Memory',
      memoryType: 'buffer',
      maxMessages: 20,
    },
  },
  ToolNode: {
    label: 'Tool',
    icon: Wrench,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Execute a tool or function',
    defaultData: {
      label: 'Tool',
      toolType: 'api',
      config: {},
    },
  },
  ScraperNode: {
    label: 'Scraper',
    icon: Globe,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Scrape web content',
    defaultData: {
      label: 'Web Scraper',
      url: '',
      selector: '',
      format: 'markdown',
    },
  },
  HTTPNode: {
    label: 'HTTP',
    icon: Wifi,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Make HTTP API calls',
    defaultData: {
      label: 'HTTP Request',
      method: 'GET',
      url: '',
      headers: {},
      body: null,
    },
  },
  CodeNode: {
    label: 'Code',
    icon: Code,
    category: 'Tools',
    color: 'var(--node-tool)',
    description: 'Run JavaScript or Python code',
    defaultData: {
      label: 'Code',
      language: 'javascript',
      code: '// Transform data here\nreturn input;',
    },
  },
  ConditionNode: {
    label: 'Condition',
    icon: GitBranch,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'If/else branching logic',
    defaultData: {
      label: 'Condition',
      conditions: [],
      trueLabel: 'Yes',
      falseLabel: 'No',
    },
  },
  LoopNode: {
    label: 'Loop',
    icon: Repeat,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Iterate or retry',
    defaultData: {
      label: 'Loop',
      maxIterations: 10,
      stopCondition: '',
    },
  },
  RouterNode: {
    label: 'Router',
    icon: Route,
    category: 'Control Flow',
    color: 'var(--node-flow)',
    description: 'Route to different paths',
    defaultData: {
      label: 'Router',
      routes: [{ label: 'Route A', condition: '' }],
    },
  },
  TransformNode: {
    label: 'Transform',
    icon: Shuffle,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Transform or map data',
    defaultData: {
      label: 'Transform',
      transformType: 'template',
      expression: '',
    },
  },
  SubAgentNode: {
    label: 'Sub-Agent',
    icon: Bot,
    category: 'Data',
    color: 'var(--node-data)',
    description: 'Call another agent',
    defaultData: {
      label: 'Sub-Agent',
      agentId: '',
      inputMapping: {},
    },
  },
  EmailNode: {
    label: 'Email',
    icon: Mail,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Send email via SMTP',
    defaultData: {
      label: 'Send Email',
      to: '',
      cc: '',
      bcc: '',
      subject: '',
      bodyTemplate: '{{input}}',
      attachFromUpstream: false,
    },
  },
  PDFNode: {
    label: 'PDF',
    icon: FileText,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Generate PDF document',
    defaultData: {
      label: 'Generate PDF',
      filenameTemplate: 'output-{{date}}',
      pageSize: 'A4',
      margins: { top: 40, bottom: 40, left: 40, right: 40 },
      includeHeader: false,
      headerText: '',
      includeFooter: false,
      footerText: '',
    },
  },
  DocxNode: {
    label: 'DOCX',
    icon: FileType,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Generate Word document',
    defaultData: {
      label: 'Generate DOCX',
      filenameTemplate: 'document-{{date}}',
      documentTitle: '',
      fontSize: 12,
      fontFamily: 'Arial',
    },
  },
  BlogNode: {
    label: 'Blog',
    icon: Globe2,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Render markdown to styled HTML',
    defaultData: {
      label: 'Generate Blog',
      filenameTemplate: 'blog-{{date}}',
      cssTheme: 'modern',
      pageTitle: '',
      metaDescription: '',
      includeTableOfContents: false,
    },
  },
  VideoNode: {
    label: 'Video',
    icon: Video,
    category: 'Actions',
    color: 'var(--node-action)',
    description: 'Compose video from media',
    defaultData: {
      label: 'Create Video',
      filenameTemplate: 'video-{{date}}',
      inputType: 'single_image_with_audio',
      audioSource: '',
      fps: 30,
      resolution: '1920x1080',
      codec: 'libx264',
    },
  },
};
